name: imgineer
services:
  postgres:
    image: postgres:15
    container_name: imgineer_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: imgineer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
